### ISSUE TITLE
es_ES spelling mistake

### ISSUE THREAD

**Issue by ayumequi** [anchorcms/anchor-translations#107]
Hello,

inside the Spanish 'es_ES' folder, on 'global.php' this line:

_'approved' => 'Aprovado_' needs to be replaced by _'approved' => 'Aprobado'_ in order to fix this spelling error.

Regards,

Daniel.

**Comment by CraigChilds94** [comment]
This is fixed; I've merged in the PR which resolves this. Thanks for spotting it!
