### ISSUE TITLE
Much Pull Requests - - Many Contribution

### ISSUE THREAD

**Issue by TimohStudios** [anchorcms/anchor-translations#64]
There are so much pull requests waiting to be added in or closed. It kind of makes me sad seeing nothing being done with all the contribution. If the Anchor team doesn't have time to figure out what to do with them, I'm happy to help.

**Comment by gautiermichelin** [comment]
+1

same here, and it's been over 7 months...

**Comment by daviddarnes** [comment]
@timohstudios has this been resolved now?

**Comment by TimohStudios** [comment]
Yep, you are right. There's a lot of PR's on this repo, a lot of PR's being opened on the main Anchor repo, no proper documentation as to where to find translations for users and no way to track how complete and up to date translations are ( #65 ).

**Comment by daviddarnes** [comment]
Will close this issue and continue discussion in #65.
