### ISSUE TITLE
No translation possibility for comment status label?

### ISSUE THREAD

**Issue by dylanmoller** [anchorcms/anchor-translations#68]
I can't seem to find the translation entry for the comment status label (on the /comments page in the administrator's panel) in the language files.

**Comment by daviddarnes** [comment]
Dependant on the language it'll be under: `anchor-translations/language_NAME/comments.php`

If it's not there you may need to create it by duplicating it from another language. I suggest you duplicate [the en_GB version](https://github.com/anchorcms/anchor-translations/blob/master/en_GB/comments.php) and change accordingly.
