### ISSUE TITLE
How can I add a new translation?

### ISSUE THREAD

**Issue by cebreus** [anchorcms/anchor-translations#78]
1) I try add a new _pull request_ on this [page](https://github.com/anchorcms/anchor-translations/compare?expand=1), as is requested in the [manual](https://github.com/anchorcms/anchor-translations). But after click on this button:

![image](https://cloud.githubusercontent.com/assets/1650647/9746475/6a3a00f0-5678-11e5-866a-424beefe870a.png)

I see this screen with inactive button.

![image](https://cloud.githubusercontent.com/assets/1650647/9746538/c56a7374-5678-11e5-82cd-c1a10042f2d5.png)

2) In other hand I try make _commit_ (success) and and _post_ (error) my changes (new folder _cs_CZ_ with translated files) in Atlasian SourceTree app (ver 1.620.0 windows). I see this error.

``git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags origin master:master
remote: Permission to anchorcms/anchor-translations.git denied to cebreus.
fatal: unable to access 'https://github.com/anchorcms/anchor-translations/': The requested URL returned error: 403``

**Comment by gautiermichelin** [comment]
Hi cebreus, 

You won't be able to do a pull request as it seems you don't have commited your changes to your github repository.
On your git client, commit your changes first. see https://www.youtube.com/watch?v=Y9dGceRGpQY for example.

When your changes are commited, you'll see that the text "This branch is even with anchorcms:master." will change on https://github.com/cebreus/anchor-translations

For now, there are no differences between your repo and anchor one.

**Comment by cebreus** [comment]
My problem is resolved. Than @gautiermichelin for help. There was more partial problems. I decide to make step by step manual for other users (like me :-).

1) Make your own **Fork** of GIThub and load it into Atlasian SourceTree

![image](https://cloud.githubusercontent.com/assets/1650647/9786939/664e9ae0-57be-11e5-93e5-3519f78c676d.png)

**For new translations – way to make _Pull request_**

2) Make changes in the files -> make _Commit_ with good description -> make _Push_ and finally go back to GIThub and make _Pull request_.

![image](https://cloud.githubusercontent.com/assets/1650647/9790167/c8b25260-57d4-11e5-92ab-95ec8d1aad05.png)
