### ISSUE TITLE
pt_PT Grammar and Spelling Mistakes.

### ISSUE THREAD

**Issue by ferrazzuk** [anchorcms/anchor-translations#98]
I tried to create a new pull request but seems its disabled at the moment. Below are some things I spotted that are not Portuguese (pt_PT) or are grammatically wrong.

comments.php
1. 'nocomments_desc' should be 'Sem comentários', the current translates to "No comments yet.", the new translates to "No comments".

global.php
1. 'save' should be 'Guardar', the current translates to "Record", the new translates to "save"
2. 'editing' should be 'Editando', the current is correct but why have to words when you can have one?
3. 'inactive' should be 'Inativo', the current is not Portuguese but Spanish.
3. 'active' should be 'Ativo', the current is not Portuguese but Spanish.

I hope this helps.

**Comment by CraigChilds94** [comment]
Fixed in previous PR
